[build]
  command = "npm run build && echo 'Build complete'"
  publish = "dist/client"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build"
  publish = "dist/client"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist/client"
